title: '[日本語版] GitHub Copilotの過去問'
summary: "GitHub Copilotの過去問集を日本語に翻訳したものです。\nGitHub Copilotの学習としてご利用ください。\n本書の概要 ▶ https://zenn.dev/aew2sbee/books/github-copilot/viewer/explanation"
topics: ['react', 'nextjs', 'ts', '初心者向け'] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - chapter01
