title: '私なりのReactのまとめ'
summary: "React公式サイトのチュートリアル ▶ https://ja.react.dev/learn 実際に動かして学んだ内容をアウトプットした内容になります
topics: ['react', 'nextjs', 'ts', '初心者向け'] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - chapter01
  - chapter02
  - chapter03
  - chapter04
